version: "beta"
name: Feedback
description: File a bug report or feature request from the customers
assignees: "CountKeepo"
body:
  - type: dropdown
    id: type
    attributes:
      label: Type of issue
      description: Is this a bug or a request?
      options:
        - Bug
        - Feature request
    validations:
      required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Whats happening? Which steps do we need to take to reproduce this error?
    validations:
      required: true
    if: ${{ form.type == 'Bug' }}

  - type: textarea
    id: feature-request
    attributes:
      label: Feature request
      description: What does the customer want?
    validations:
      required: true
    if: ${{ form.type == 'Feature request' }}
